DROP TABLE IF EXISTS T_DETECTION;
DROP TABLE IF EXISTS T_BASE_DETECTION;
DROP TABLE IF EXISTS T_DEVICE;
CREATE TABLE T_DEVICE
(
    DEVICE_UUID  UUID PRIMARY KEY,
    DEVICE_TYPE  VARCHAR2(50) NOT NULL,
    DEVICE_MODEL VARCHAR(50)  NOT NULL,
    OS_VERSION   VARCHAR(50)  NOT NULL
);

CREATE TABLE T_DETECTION
(
    DETECTION_UUID UUID PRIMARY KEY,
    TIME_REPORTED  TIMESTAMP   NOT NULL,
    TIME_INSERTED  TIMESTAMP   NOT NULL,
    TIME_RESOLVED  TIMESTAMP,
    STATUS         VARCHAR(50) NOT NULL,
    APP_NAME       VARCHAR(50) NOT NULL,
    APP_TYPE       VARCHAR(50) NOT NULL,
    DEVICE_UUID    UUID        NOT NULL,
    FOREIGN KEY (DEVICE_UUID) REFERENCES T_DEVICE
);

CREATE TABLE T_BASE_DETECTION
(
    DETECTION_UUID UUID PRIMARY KEY,
    TIME_REPORTED  TIMESTAMP NOT NULL,
    TIME_INSERTED  TIMESTAMP NOT NULL,
    DEVICE_UUID    UUID      NOT NULL,
    FOREIGN KEY (DEVICE_UUID) REFERENCES T_DEVICE
);
